---
- name: Update SSL certificate on GWEFA appliances
  hosts: all
  become: true
  become_user: exadmn
  tasks:
    - name: "Create required directories in /etc/letsencrypt2"
      become: true
      become_user: root
      file:
        path: "/etc/letsencrypt2/{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0711
      with_items:
        - account
        - certs
        - csrs
        - keys

    - name: "Generate a Let's Encrypt account key"
      shell: "if [ ! -f {{ letsencrypt_account_key }} ]; then openssl genrsa 4096 | sudo tee {{ letsencrypt_account_key }}; fi"

    - name: "Generate Let's Encrypt private key"
      shell: "openssl genrsa 4096 | sudo tee /etc/letsencrypt2/keys/{{ inventory_hostname }}.key"

    - name: "Create temporary OpenSSL config with SAN"
      become: true
      become_user: root
      copy:
        content: |
          [ req ]
          default_bits       = 2048
          distinguished_name = req_distinguished_name
          req_extensions     = req_ext
          prompt             = no

          [ req_distinguished_name ]
          CN = {{ inventory_hostname }}

          [ req_ext ]
          subjectAltName = @alt_names

          [ alt_names ]
          DNS.1 = {{ inventory_hostname }}
        dest: /tmp/openssl-{{ inventory_hostname }}.cnf
        mode: "0644"

    - name: "Generate Let's Encrypt CSR"
      become: true
      become_user: root
      shell: "openssl req -new -sha256 -key /etc/letsencrypt2/keys/{{ inventory_hostname }}.key -config /tmp/openssl-{{ inventory_hostname }}.cnf -out /etc/letsencrypt2/csrs/{{ inventory_hostname }}.csr"
      args:
        executable: /bin/bash

    - name: "Remove temporary OpenSSL config"
      become: true
      become_user: root
      file:
        path: /tmp/openssl-{{ inventory_hostname }}.cnf
        state: absent

    - name: "Begin Let's Encrypt challenges"
      become: true
      become_user: root
      acme_certificate:
        acme_directory: "{{ acme_directory }}"
        acme_version: "{{ acme_version }}"
        account_key_src: "{{ letsencrypt_account_key }}"
        account_email: "{{ acme_email }}"
        terms_agreed: 1
        challenge: "{{ acme_challenge_type }}"
        csr: "{{ letsencrypt_csrs_dir }}/{{ inventory_hostname }}.csr"
        dest: "{{ letsencrypt_certs_dir }}/{{ inventory_hostname }}.crt"
        fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ inventory_hostname }}.crt"
        remaining_days: 91
      register: acme_challenge

    - name: "Debug acme_challenge"
      debug:
        var: acme_challenge

    - name: "Create .well-known/acme-challenge directory"
      become: true
      become_user: root
      file:
        path: /var/www/html/.well-known/acme-challenge
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: "Implement http-01 challenge files"
      become: true
      become_user: root
      copy:
        content: "{{ item.challenges[0].http-01.resource_value }}"
        dest: "/var/www/html/{{ item.identifier.value }}/{{ item.challenges[0].http-01.resource }}"
        owner: root
        group: root
        mode: 0644
      with_items: "{{ acme_challenge['authorizations'].values() }}"

    - name: Stop iptables service
      service:
        name: iptables
        state: stopped

    - name: "Complete Let's Encrypt challenges"
      become: true
      become_user: root
      acme_certificate:
        acme_directory: "{{ acme_directory }}"
        acme_version: "{{ acme_version }}"
        account_key_src: "{{ letsencrypt_account_key }}"
        account_email: "{{ acme_email }}"
        challenge: "{{ acme_challenge_type }}"
        csr: "{{ letsencrypt_csrs_dir }}/{{ inventory_hostname }}.csr"
        dest: "{{ letsencrypt_certs_dir }}/{{ inventory_hostname }}.crt"
        chain_dest: "{{ letsencrypt_certs_dir }}/chain_{{ inventory_hostname }}.crt"
        fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ inventory_hostname }}"
        data: "{{ acme_challenge }}"

    - name: Start iptables service
      service:
        name: iptables
        state: started
