---
- name: Update SSL certificate on GWEFA appliances
  hosts: all
  become: true
  become_user: exadmn
  tasks:
    - name: Stop iptables service
      service:
        name: iptables
        state: stopped

    - name: Install certbot and generate cert
      ansible.builtin.command: "{{ certbot_script }} certonly --noninteractive --agree-tos --standalone --email {{ certbot_admin_email }} -d {{ inventory_hostname }}"
      args:
        creates: "{{ certbot_output_dir }}"

    - name: Restart httpd webserver
      service:
        name: httpd
        state: restarted

    - name: Start iptables service
      service:
        name: iptables
        state: started
